FROM python:3.11-slim

WORKDIR /app

COPY frontend/requirements.txt .

RUN pip3 install --no-cache-dir -r requirements.txt

COPY shared/RequestDto.py .
COPY frontend/main.py .

CMD ["python", "main.py"]