FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

RUN apt-get update 
RUN apt-get install ffmpeg -y
RUN apt-get install nodejs npm -y
RUN apt-get install proxychains -y

WORKDIR /app

# Dependencies zuerst (Docker Cache)
COPY backend/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY shared/RequestDto.py .
COPY backend/main.py .

# Startkommando
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]